module.exports = {
  searchQueryStrings: [
    '100daysofcode',
    '301daysofcode',
    'freecodecamp',
    'github',
    'gitlab',
    'vscode',
    'visual studio code',
    'atomio',
    'atom.io',
    'nodejs',
    'node.js',
    'npmjs',
    'npm.js',
    'vuejs',
    'vue.js',
    'inferno_js',
    'infernojs',
    'inferno.js',
    'laravel',
    'laravelphp',
    'svelte.js',
    'sveltejs',
    'docker',
    'ionic',
    '.json',
    'blockchain',
    'es6',
    'webpack',
    'flexbox',
    'javascript'
  ]
}
